site_name: NeutroWater Docs
site_url: https://example.com/
theme:
    name : readthedocs
    features:
      - navigation.sections
      - navigation.indexes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  
plugins:
  - glightbox
  - mkdocstrings
  - search

nav:

  - User Guide: user_guide.md

  - Theory and Methodology: theory.md 

  - Results: results.md

  - API Reference: reference.md

  - Citings: citings.md



  


